name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "terraform-job"
    outputs:
      host: ${{ steps.terraform_output.outputs.public_ip }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: terraform_output
        run: |
          echo public_ip=$(terraform output instance_public_ip | tr -d '"') >> $GITHUB_OUTPUT
          mkdir terraform_output
          echo $(terraform output instance_public_ip | tr -d '"') >> terraform_output/output.txt
          aws s3 cp terraform_output/output.txt s3://kajal-bucket-test/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

  ci-cd:
    needs: [terraform]
    uses: kajalp238/esop-deploy-demo/.github/workflows/main.yml@main
    secrets:
      KAJAL_EC2_SSH_KEY: ${{ secrets.KAJAL_EC2_SSH_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}