name: build-test-deploy

on:
  push:
    branches: [ "main" ]

jobs:
 
  build:
    name: "build the application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run:
          ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Test
        run: ./gradlew test

  deploy:
    name: "deploy the application"
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0
      - name: Copy jar file to ec2 instance
        env:
          SSH_PRIVATE_KEY: ${{secrets.KAJAL_EC2_SSH_KEY}}
          SSH_HOST: 44.202.123.63
        run: |
          eval `ssh-agent`
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          echo "add"
          scp -T -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$SSH_HOST:~
          echo "priv key"
          ssh -T -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t '
            pid=$(fuser 8080/tcp)
            if [ $pid ]
            then
            fuser -k 8080/tcp
            fi
            curl -s 'https://get.sdkman.io' | bash
            source "/.sdkman/bin/sdkman-init.sh"
            sdk install java 17.0.6-amzn
            java -jar esop-0.1-all.jar > /dev/null
          '
